#!/usr/bin/env ruby 

#
# To use Octopus, please add the directory path to this file to your PATH
# For Bash:
#   Add export PATH=$PATH:/path/to/oct/source to your ~/.bashrc
#

# to run this file, add the `pwd` to your path.
#
require "#{File.dirname(__FILE__)}/ui/UserInterface.rb"

UserInterface.new.main(ARGV)
